name: deploy

on:
  push:
   branches:
    - master
    - demo-source

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      GH_DEPLOY_TOKEN: ${{secrets.GH_DEPLOY_TOKEN}}
    steps:
      - name: Checkout branch
        uses: actions/checkout@master
        with:
          ref: demo-source
      - name: Use Node.js 10.x
        uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - name: Prepare source
        run: |
          git clone -b master "https://${GH_DEPLOY_TOKEN}@github.com/rayspock/hexo-theme-aircv.git" themes/aircv
          cp themes/aircv/_config.yml.example themes/aircv/_config.yml
          npm install
      - name: Run hexo generate
        run: |
          npm i -g hexo-cli
          hexo generate
      - name: Run hexo deploy
        run: |
          git config --global user.name 'rayspock'
          git config --global user.email 'rayspock@protonmail.com'
          sed -i "s/<token>/${GH_DEPLOY_TOKEN}/g" ./_config.yml
          hexo deploy
